apiVersion: v1
kind: Namespace
metadata:
  name: deploy
  labels:
    pod-security.kubernetes.io/enforce: privileged
    #pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.23