apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow_pod_read
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: ["create", "get", "watch", "list", "patch", "delete", "deletecollection", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow_pod_read_bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow_pod_read
subjects:
- kind: ServiceAccount
  name: seckube