apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-to-deploy
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: deploy
