# Role avec aucune permission
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no-access-role
rules: []

---
# RoleBinding pour associer le service account par défaut au Role sans permission
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restrict-default-sa
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: no-access-role
  apiGroup: rbac.authorization.k8s.io