apiVersion: v1
kind: Pod
metadata:
  name: nonroot-priv
spec:
  containers:
  - name: nonroot-priv
    image: leonelfeukouo/snyky
    volumeMounts:
      - mountPath: /chroot
        name: host
    securityContext:
      runAsUser: 999
      privileged: true
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory